# Generated by Django 4.0.4 on 2022-06-07 20:01

import bank.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, default=bank.utils.create_new_account_number, editable=False, max_length=26, unique=True)),
                ('account_type', models.CharField(choices=[('Personal account', 'Personal'), ('Savings account', 'Savings'), ('Foreign currency account', 'Foreign')], max_length=50)),
                ('balance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, default=bank.utils.create_new_card_number, editable=False, max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('Debit card', 'Debit'), ('Credit card', 'Credit')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11)),
                ('accounts', models.ManyToManyField(to='bank.account')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.address')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.card'),
        ),
    ]
